/*
      Compilation
          V
          V Just Finished Compling and ready for Execution
          V
   Global Execution Context is Formed(Top level code (not inside function) will run first)
          V
          V 
          V
   Execution of top-level code
(Inside Global Execution Context)


What is Execution Context?

Environment in which piece of Javscript is executed. Stores all the necessary information
for some code to be executed.

Note: 


*/
